### ISSUE TITLE
how to download/prepare datasets

### ISSUE THREAD

**Issue by shahrukhx01** [knoriy/CLARA#10]
@knoriy First of all thanks for the great contribution. I am trying to reproduce the results using the medium model checkpoint on the underlying datasets from the paper. However, I am unsure how the datasets can accessed. Could you please point me to how I can prepare/download the datasets? Thank you!

**Comment by shahrukhx01** [comment]
FYI: The S3 bucket is not publicly accessible unfortunately.
<img width="1390" alt="Screenshot 2023-11-14 at 02 52 47" src="https://github.com/knoriy/CLARA/assets/6007894/076676cc-e440-47b6-b5ea-24b3142c9d4e">

**Comment by knoriy** [comment]
Unfortunately, we can't share the processed data used in training CLARA, but you can use the [Laion audio dataset](https://github.com/knoriy/audio-dataset) scripts to download and process the data as needed.

Most of the datasets are publicly available, and the CLARA codebase uses [TorchData](https://github.com/pytorch/data)/webdataset format. In the future, I'd like to release a pipeline to perform augmentation and data processing.
